# Generated by Django 4.1.4 on 2022-12-19 10:03

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_voucher_signature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='voucher_signature',
        ),
        migrations.AddField(
            model_name='voucher_history',
            name='signature',
            field=jsignature.fields.JSignatureField(blank=True, null=True),
        ),
    ]
