# Generated by Django 4.1.4 on 2022-12-28 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        ('voucher', '0003_delete_voucher_signature_voucher_history_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='eachtime',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=21),
        ),
        migrations.AddField(
            model_name='voucher',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=21),
        ),
        migrations.AlterField(
            model_name='voucher_history',
            name='sales_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.sales_transaction'),
        ),
    ]
