# Generated by Django 4.1.4 on 2022-12-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0005_remove_voucher_history_voucher_deduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='tqty',
            field=models.IntegerField(default=1),
        ),
    ]
