# Generated by Django 4.1.4 on 2022-12-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendliness', models.IntegerField()),
                ('cleaniness', models.IntegerField()),
                ('price_satisfaction', models.IntegerField()),
                ('service_satisfaction', models.IntegerField()),
                ('overall_satisfaction', models.IntegerField()),
                ('remarks', models.TextField()),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
