# Generated by Django 4.1.4 on 2022-12-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_info',
            name='inner_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
