# Generated by Django 4.1.4 on 2022-12-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_services_department'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[(5, 'Missed'), (4, 'Complete'), (2, 'Rejected'), (1, 'Upcoming'), (3, 'Cancel')], max_length=1),
        ),
        migrations.AlterField(
            model_name='appointment_service',
            name='appointment',
            field=models.ManyToManyField(blank=True, null=True, to='appointment.appointment'),
        ),
        migrations.AlterField(
            model_name='appointment_service',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='manager.services'),
        ),
    ]
