# Generated by Django 4.1.4 on 2022-12-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_employee_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[(2, 'Rejected'), (1, 'Upcoming'), (5, 'Missed'), (4, 'Complete'), (3, 'Cancel')], max_length=1),
        ),
    ]
