# Generated by Django 4.1.4 on 2022-12-27 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        ('credit', '0002_credits_history_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits_history',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.sales_transaction'),
        ),
    ]
