# Generated by Django 4.1.4 on 2022-12-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_alter_credits_history_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='credits_history',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
