# Generated by Django 4.1.4 on 2022-12-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_sales_transaction_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_transaction',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
