# Generated by Django 4.1.4 on 2022-12-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_sales_transaction_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_services',
            name='service_department',
            field=models.CharField(choices=[('HAIR', 'HAIR'), ('BEAUTY', 'BEAUTY')], default='HAIR', max_length=25),
        ),
    ]
