# Generated by Django 4.1.4 on 2023-02-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_sales_services_service_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_services',
            name='service_department',
            field=models.CharField(choices=[('HAIR', 'HAIR'), ('BEAUTY', 'BEAUTY'), ('HAIR PRODUCT', 'HAIR PRODUCT'), ('BEAUTY PRODUCT', 'BEAUTY PRODUCT'), ('CREDIT TOP UP', 'CREDIT TOP UP')], default='HAIR', max_length=25),
        ),
        migrations.AlterField(
            model_name='sales_transaction',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CREDIT', 'CREDIT'), ('CARDS', 'CARDS'), ('NETS', 'NETS'), ('GRAB', 'GRAB'), ('PAYNOW', 'PAYNOW'), ('OTHERS', 'OTHERS')], max_length=25),
        ),
    ]
