# Generated by Django 4.1.4 on 2022-12-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_userinfo_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.PositiveBigIntegerField(choices=[(1, 'Customer'), (2, 'Employee'), (4, 'Manager'), (3, 'Assistant')], default='1'),
        ),
    ]
