# Generated by Django 4.1.4 on 2022-12-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_userinfo_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.PositiveBigIntegerField(choices=[(2, 'Employee'), (3, 'Assistant'), (4, 'Manager'), (1, 'Customer')], default='1'),
        ),
    ]
