# Generated by Django 4.1.4 on 2022-12-17 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_profile_pic_user_alter_userinfo_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cemail', models.EmailField(max_length=254)),
                ('cphone', models.CharField(max_length=8)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.PositiveBigIntegerField(choices=[(2, 'Employee'), (4, 'Manager'), (1, 'Customer'), (3, 'Assistant')], default='1'),
        ),
    ]
