# Generated by Django 4.1.4 on 2022-12-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_contact_alter_userinfo_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_ack',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.PositiveBigIntegerField(choices=[(1, 'Customer'), (4, 'Manager'), (2, 'Employee'), (3, 'Assistant')], default='1'),
        ),
    ]
