# Generated by Django 4.1.4 on 2022-12-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_contact_is_ack_alter_userinfo_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_pic',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.PositiveBigIntegerField(choices=[(1, 'Customer'), (2, 'Employee'), (3, 'Assistant'), (4, 'Manager')], default='1'),
        ),
    ]
